### ISSUE TITLE
Buildathon

### ISSUE THREAD

**Issue by dingwilson** [dingwilson/Hackathon-Packing-List#1]
# Hackathon Packing List

As an experienced hacker (over 30 hackathons in the past 2 years), I have developed a list of things to pack for hackathons, and am sharing this with the world. Feel free to fork it or make pull requests to add your own items.

1. [Essentials](#essentials)
2. [Extras](#extras)
3. [Hygiene](#hygiene)
4. [Flights](#flights)
5. [Hardware](#hardware)
	- [Basics](#basics)
	- [Tools](#tools)
	- [I/O](#io)
6. [ToDos](#todos)

## Essentials
- [x] Computer and Charger
- [x] Phone and Charger
- [x] Smartwatch and Charger
- [x] Backpack/Storage
- [x] Earphones/Headphones
- [x] Identification (Student ID, Drivers License, etc.)
- [x] Dongles/Adapters (Lightning, USB-C, etc.)
- [x] Medications
- [x] Wallet (Hackathons are usually free, but it doesn't hurt to carry some cash and your ID)
- [x] Keys 

## Extras
- [x] Surge Protector
- [x] Battery Bank
- [x] Sleeping Bag/Blanket/Pillow
- [x] Mouse/Mousepad
- [x] Keyboard
- [x] USB Flashdrives
- [ ] Pen/Pencil and Paper/Sticky Notes
- [x] Extra Cords
- [ ] Pajamas
- [ ] Resumes

## Hygiene
- [ ] Toothbrush/Toothpaste
- [x] Deodorant
- [x] Change of Clothing

## Flights
- [ ] Plane Tickets
- [ ] Identification (Passport, Drivers License, etc.)
- [ ] Travel Reimbursement/Etc. Forms
- [ ] Neck/Hoodie Pillow

## Hardware
(Thanks to Jeff Zhao for showing me this [blog post](http://blog.cyrusroshan.com/2016/01/02/a-hardware-hackers-kit) by [CyrusRoshan](https://github.com/CyrusRoshan). I totally copied the hardware list on the blog.)

### Basics
- [x] Dev Board (Arduino, Raspberry Pi, Edison, Photon, etc.)
- [x] Cables
- [x] Breadboards
- [x] Jumper Wires/Alligator Clips
- [x] Resistors

### Tools
- [x] Needle Nose Pliers
- [x] Wire Cutters
- [x] Screwdrivers
- [x] Superglue
- [x] Electric Tape
- [x] Zipties
- [x] Multimeter

##### Small Components
- [x] LEDs
- [x] Photoresistors
- [x] Reflective IR
- [x] IR Transmitter/Reciever LEDs
- [x] Transistors
- [x] Capacitors
- [x] Piezos
- [x] Humidity sensor
- [x] Temperature sensor
- [x] Hall sensors
- [x] Vibration Motors
- [x] Tilt/vibration sensors
- [x] DC Motors
- [x] Push button switches
- [ ] Flex sensors (a bit more expensive, I’d only get one)
- [ ] Force sensitive resistors (same as above)

##### Large Components
- [x] Servos
- [ ] Pulse sensor
- [x] Ultrasonic range sensors
- [ ] Gyro/Accelerometer (usually have both on the same breakout board)
- [x] LCD screen (preferably with I2C for less wires)
- [ ] Bluetooth module (you’ll need one with BLE support for iPhones)

##### Additional Power
- [x] Relay module
- [x] Breadboard psu
- [x] 9v Batteries (for powering motors that needs more power. Use with transistor to switch on/off)
- [x] Rechargeable power bank (for when you want to power your dev board without a laptop)

## ToDos
- [x] Update OS, IDEs, and all other software
- [x] Confirm venue location and time
- [x] Confirm transportation arrangements
- [x] Set multiple alarms and get a good nights sleep!
