### ISSUE TITLE
s

### ISSUE THREAD

**Issue by bearcott** [dingwilson/Hackathon-Packing-List#5]
1. [Essentials](#essentials)
2. [Extras](#extras)
3. [Hygiene](#hygiene)
4. [Flights](#flights)
5. [Hardware](#hardware)
	- [Basics](#basics)
	- [Tools](#tools)
	- [I/O](#io)
6. [ToDos](#todos)

## Essentials
- [ ] Computer and Charger
- [ ] Phone and Charger
- [ ] Smartwatch and Charger
- [ ] Backpack/Storage
- [ ] Earphones/Headphones
- [ ] Identification (Student ID, Drivers License, etc.)
- [ ] Dongles/Adapters (Lightning, USB-C, etc.)
- [ ] Medications
- [ ] Wallet (Hackathons are usually free, but it doesn't hurt to carry some cash and your ID)
- [ ] Keys 

## Extras
- [ ] Surge Protector
- [ ] Battery Bank
- [ ] Sleeping Bag/Blanket/Pillow
- [ ] Mouse/Mousepad
- [ ] Keyboard
- [ ] USB Flashdrives
- [ ] Pen/Pencil and Paper/Sticky Notes
- [ ] Extra Cords
- [ ] Pajamas
- [ ] Resumes

## Hygiene
- [ ] Toothbrush/Toothpaste
- [ ] Deodorant
- [ ] Change of Clothing

## Flights
- [ ] Plane Tickets
- [ ] Identification (Passport, Drivers License, etc.)
- [ ] Travel Reimbursement/Etc. Forms
- [ ] Neck/Hoodie Pillow

### Basics
- [ ] Dev Board (Arduino, Raspberry Pi, Edison, Photon, etc.)
- [ ] Cables
- [ ] Breadboards
- [ ] Jumper Wires/Alligator Clips
- [ ] Resistors

### Tools
- [ ] Needle Nose Pliers
- [ ] Wire Cutters
- [ ] Screwdrivers
- [ ] Superglue
- [ ] Electric Tape
- [ ] Zipties
- [ ] Multimeter

##### Small Components
- [ ] LEDs
- [ ] Photoresistors
- [ ] Reflective IR
- [ ] IR Transmitter/Reciever LEDs
- [ ] Transistors
- [ ] Capacitors
- [ ] Piezos
- [ ] Humidity sensor
- [ ] Temperature sensor
- [ ] Hall sensors
- [ ] Vibration Motors
- [ ] Tilt/vibration sensors
- [ ] DC Motors
- [ ] Push button switches
- [ ] Flex sensors (a bit more expensive, I’d only get one)
- [ ] Force sensitive resistors (same as above)

##### Large Components
- [ ] Servos
- [ ] Pulse sensor
- [ ] Ultrasonic range sensors
- [ ] Gyro/Accelerometer (usually have both on the same breakout board)
- [ ] LCD screen (preferably with I2C for less wires)
- [ ] Bluetooth module (you’ll need one with BLE support for iPhones)

##### Additional Power
- [ ] Relay module
- [ ] Breadboard psu
- [ ] 9v Batteries (for powering motors that needs more power. Use with transistor to switch on/off)
- [ ] Rechargeable power bank (for when you want to power your dev board without a laptop)

## ToDos
- [ ] Update OS, IDEs, and all other software
- [ ] Confirm venue location and time
- [ ] Confirm transportation arrangements
- [ ] Set multiple alarms and get a good nights sleep!

**Comment by dingwilson** [comment]
Please feel free to submit a PR if you would like to add something to the Hackathon Packing List. Thanks~

**Comment by bearcott** [comment]
how about i make a pr for my massive fuckin dong, ahahaa lmao

**Comment by bearcott** [comment]
🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆🍆 heheheheheheheheheheehehheheh my maaasssive epeen
