### ISSUE TITLE
Hacktober

### ISSUE THREAD

**Issue by dingwilson** [dingwilson/Hackathon-Packing-List#6]
1. [Essentials](#essentials)
2. [Extras](#extras)
3. [Hygiene](#hygiene)
4. [Flights](#flights)
5. [Hardware](#hardware)
	- [Basics](#basics)
	- [Tools](#tools)
	- [I/O](#io)
6. [ToDos](#todos)

## Essentials
- [x] Computer and Charger
- [x] Phone and Charger
- [x] Smartwatch and Charger
- [x] Backpack/Storage
- [x] Earphones/Headphones
- [x] Identification (Student ID, Drivers License, etc.)
- [x] Dongles/Adapters (Lightning, USB-C, etc.)
- [x] Medications
- [x] Wallet (Hackathons are usually free, but it doesn't hurt to carry some cash and your ID)
- [x] Keys 

## Extras
- [x] Surge Protector
- [ ] Battery Bank
- [x] Sleeping Bag/Blanket/Pillow
- [x] Mouse/Mousepad
- [x] Keyboard
- [x] USB Flashdrives
- [x] Pen/Pencil and Paper/Sticky Notes
- [x] Extra Cords
- [ ] Pajamas
- [ ] Resumes

## Hygiene
- [ ] Toothbrush/Toothpaste
- [x] Deodorant
- [x] Change of Clothing

## Flights
- [ ] Plane Tickets
- [ ] Identification (Passport, Drivers License, etc.)
- [x] Travel Reimbursement/Etc. Forms
- [ ] Neck/Hoodie Pillow

### Basics
- [ ] Dev Board (Arduino, Raspberry Pi, Edison, Photon, etc.)
- [ ] Cables
- [ ] Breadboards
- [ ] Jumper Wires/Alligator Clips
- [ ] Resistors

### Tools
- [ ] Needle Nose Pliers
- [ ] Wire Cutters
- [ ] Screwdrivers
- [ ] Superglue
- [ ] Electric Tape
- [ ] Zipties
- [ ] Multimeter

##### Small Components
- [ ] LEDs
- [ ] Photoresistors
- [ ] Reflective IR
- [ ] IR Transmitter/Reciever LEDs
- [ ] Transistors
- [ ] Capacitors
- [ ] Piezos
- [ ] Humidity sensor
- [ ] Temperature sensor
- [ ] Hall sensors
- [ ] Vibration Motors
- [ ] Tilt/vibration sensors
- [ ] DC Motors
- [ ] Push button switches
- [ ] Flex sensors (a bit more expensive, I’d only get one)
- [ ] Force sensitive resistors (same as above)

##### Large Components
- [ ] Servos
- [ ] Pulse sensor
- [ ] Ultrasonic range sensors
- [ ] Gyro/Accelerometer (usually have both on the same breakout board)
- [ ] LCD screen (preferably with I2C for less wires)
- [ ] Bluetooth module (you’ll need one with BLE support for iPhones)

##### Additional Power
- [ ] Relay module
- [ ] Breadboard psu
- [ ] 9v Batteries (for powering motors that needs more power. Use with transistor to switch on/off)
- [ ] Rechargeable power bank (for when you want to power your dev board without a laptop)

## ToDos
- [x] Update OS, IDEs, and all other software
- [x] Confirm venue location and time
- [x] Confirm transportation arrangements
- [x] Set multiple alarms and get a good nights sleep!
